name: special_e2e

on:
  push:
    branches:
      - main
      - v0.*
  pull_request:
    branches:
      - main
      - v0.*
    paths:
      - "**/*.py"
      - .github/workflows/special_e2e.yml
      - "tests/special_e2e/**"
